# Generated by Django 4.0.2 on 2022-02-19 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Top100Movies', '0001_initial'),
    ]

    operations = [
    ]
